[package]
name = "server"
version = "0.1.0"
authors = ["IWANABETHATGUY <974153916@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.13.3"
log = "0.4"
env_logger = "0.6.1"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"